# Generated by Django 6.0.7 on 2026-08-04 17:47

import django.db.models.deletion
import django.db.models.manager
import educore.core.db
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_stepup_isolation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('price_per_staff_per_term', models.PositiveIntegerField(help_text='Minor units. Never a float.')),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('max_staff', models.PositiveIntegerField(blank=True, null=True)),
                ('modules', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'platform_plan',
                'ordering': ['price_per_staff_per_term'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=16)),
                ('started_on', models.DateField()),
                ('trial_ends_on', models.DateField(blank=True, null=True)),
                ('current_period_end', models.DateField(blank=True, null=True)),
                ('cancelled_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='platform.plan')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='core.school')),
            ],
            options={
                'db_table': 'platform_subscription',
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('staff', 'Staff'), ('students', 'Students'), ('guardians', 'Guardians')], max_length=16)),
                ('status', models.CharField(choices=[('validated', 'Validated (dry run)'), ('applied', 'Applied'), ('rejected', 'Rejected')], max_length=16)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_ok', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.membership')),
            ],
            options={
                'db_table': 'platform_importbatch',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
                'constraints': [models.UniqueConstraint(fields=('school', 'id'), name='platform_importbatch_school_id_uniq')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measured_on', models.DateField(db_index=True)),
                ('active_staff', models.PositiveIntegerField(default=0)),
                ('active_students', models.PositiveIntegerField(default=0)),
                ('lessons_recorded', models.PositiveIntegerField(default=0)),
                ('notifications_sent', models.PositiveIntegerField(default=0)),
                ('storage_bytes', models.BigIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='core.school')),
            ],
            options={
                'db_table': 'platform_usagerecord',
                'ordering': ['-measured_on'],
                'constraints': [models.UniqueConstraint(fields=('school', 'measured_on'), name='platform_usage_school_date_uniq')],
            },
        ),
    ]
