# Generated by Django 6.0.7 on 2026-08-04 17:03

import django.db.models.deletion
import django.db.models.manager
import educore.core.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_tenant_isolation'),
        ('core', '0005_refreshtoken_isolation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=16)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academics.department')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'db_table': 'academics_subject',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periods_per_week', models.PositiveSmallIntegerField(default=1)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.academicyear')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.level')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.subject')),
            ],
            options={
                'db_table': 'academics_course',
                'ordering': ['level__sequence', 'subject__name'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='academics_subject_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='academics_subject_school_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='academics_course_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('subject', 'level', 'academic_year'), name='academics_course_unique_offering'),
        ),
    ]
