# Generated by Django 6.0.7 on 2026-09-08 14:17

import django.db.models.deletion
import django.db.models.manager
import educore.core.db
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_mfa_secret_encrypted_field'),
        ('students', '0003_tenant_isolation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('purpose', models.TextField(blank=True)),
                ('destination', models.CharField(max_length=200)),
                ('departs_at', models.DateTimeField()),
                ('returns_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('departed', 'Departed'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('actual_departed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_returned_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.membership')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.membership')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'db_table': 'movement_trip',
                'ordering': ['-departs_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TripParticipant',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departure_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('return_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_participations', to='students.student')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='movement.trip')),
            ],
            options={
                'db_table': 'movement_tripparticipant',
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TripSupervisor',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_lead', models.BooleanField(default=False)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.membership')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='movement.trip')),
            ],
            options={
                'db_table': 'movement_tripsupervisor',
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PassOut',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('medical', 'Medical'), ('family', 'Family'), ('weekend_home', 'Weekend at home'), ('official', 'Official school business'), ('other', 'Other')], max_length=16)),
                ('destination', models.CharField(max_length=200)),
                ('responsible_person', models.CharField(max_length=200)),
                ('narrative', models.TextField(blank=True)),
                ('expected_return_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('denied', 'Denied'), ('departed', 'Departed'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='requested', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.membership')),
                ('departure_gate_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.gateevent')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.membership')),
                ('return_gate_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.gateevent')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pass_outs', to='students.student')),
            ],
            options={
                'db_table': 'movement_passout',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
                'indexes': [models.Index(fields=['school', 'status', 'expected_return_at'], name='movement_passout_overdue_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'id'), name='movement_passout_school_id_uniq'), models.UniqueConstraint(condition=models.Q(('status__in', ('requested', 'approved', 'departed'))), fields=('student',), name='movement_passout_one_open_per_student')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['school', 'status', 'returns_at'], name='movement_trip_overdue_idx'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='movement_trip_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='tripparticipant',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='movement_tripparticipant_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='tripparticipant',
            constraint=models.UniqueConstraint(fields=('trip', 'student'), name='movement_trip_participant_uniq'),
        ),
        migrations.AddConstraint(
            model_name='tripsupervisor',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='movement_tripsupervisor_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='tripsupervisor',
            constraint=models.UniqueConstraint(fields=('trip', 'membership'), name='movement_trip_supervisor_uniq'),
        ),
        migrations.AddConstraint(
            model_name='tripsupervisor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_lead', True)), fields=('trip',), name='movement_trip_one_lead'),
        ),
    ]
