# Generated by Django 6.0.7 on 2026-08-04 10:45

import django.db.models.deletion
import django.db.models.manager
import educore.core.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_audit_append_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='beacon_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campus',
            name='wifi_bssid_hashes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_id', models.UUIDField(db_index=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.device')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='core.membership')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'db_table': 'core_refreshtoken',
                'abstract': False,
                'base_manager_name': 'all_tenants',
                'indexes': [models.Index(fields=['membership', 'expires_at'], name='core_refresh_member_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'id'), name='core_refreshtoken_school_id_uniq')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
    ]
