# Generated by Django 6.0.7 on 2026-08-09 15:07

import django.db.models.deletion
import django.db.models.manager
import educore.core.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_stepup_isolation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteToken',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to='core.membership')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'db_table': 'core_invitetoken',
                'abstract': False,
                'base_manager_name': 'all_tenants',
                'indexes': [models.Index(fields=['membership', 'expires_at'], name='core_invite_member_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'id'), name='core_invitetoken_school_id_uniq')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
    ]
