# Generated by Django 6.0.7 on 2026-08-04 17:03

import django.db.models.deletion
import django.db.models.manager
import educore.core.db
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_subject_course_and_more'),
        ('core', '0005_refreshtoken_isolation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('sick', 'Sick')], max_length=16)),
                ('method', models.CharField(choices=[('teacher_marked', 'Marked by teacher'), ('student_scan', 'Scanned by student'), ('gate', 'Gate scan'), ('inferred', 'Inferred')], default='teacher_marked', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'students_studentattendance',
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_number', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('residency', models.CharField(choices=[('day', 'Day scholar'), ('boarding', 'Boarder')], default='day', max_length=16)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('suspended', 'Suspended'), ('transferred', 'Transferred out'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn')], default='enrolled', max_length=16)),
                ('admitted_on', models.DateField(blank=True, null=True)),
                ('scan_code', models.CharField(blank=True, max_length=64)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'db_table': 'students_student',
                'ordering': ['full_name'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GuardianLink',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=16)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('receives_notifications', models.BooleanField(default=True)),
                ('has_portal_access', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='core.membership')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.membership')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='students.student')),
            ],
            options={
                'db_table': 'students_guardianlink',
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GateEvent',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('in', 'Arrival'), ('out', 'Departure')], max_length=8)),
                ('method', models.CharField(choices=[('qr', 'QR code'), ('nfc', 'NFC card'), ('barcode', 'Barcode'), ('manual', 'Recorded manually')], default='qr', max_length=16)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('client_event_id', models.UUIDField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.campus')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_events', to='students.student')),
            ],
            options={
                'db_table': 'students_gateevent',
                'ordering': ['occurred_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='academics.classgroup')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='academics.term')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='students.student')),
            ],
            options={
                'db_table': 'students_enrolment',
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
    ]
