# Generated by Django 6.0.7 on 2026-08-04 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_refreshtoken_isolation'),
        ('students', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='lesson_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='register', to='timetable.lessoninstance'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.membership'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='school',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='students_student_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'admission_number'), name='students_student_admission_uniq'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('scan_code', ''), _negated=True), fields=('school', 'scan_code'), name='students_student_scan_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='guardianlink',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='students_guardianlink_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='guardianlink',
            constraint=models.UniqueConstraint(fields=('student', 'membership'), name='students_guardian_unique_link'),
        ),
        migrations.AddConstraint(
            model_name='guardianlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_contact', True)), fields=('student',), name='students_guardian_one_primary'),
        ),
        migrations.AddConstraint(
            model_name='gateevent',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='students_gateevent_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='gateevent',
            constraint=models.UniqueConstraint(fields=('school', 'client_event_id'), name='students_gate_client_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='students_enrolment_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'term'), name='students_enrolment_one_active_per_term'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['school', 'date', 'status'], name='students_attendance_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='students_studentattendance_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('lesson_instance__isnull', False)), fields=('student', 'lesson_instance'), name='students_attendance_lesson_uniq'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('lesson_instance__isnull', True)), fields=('student', 'date'), name='students_attendance_day_uniq'),
        ),
    ]
