# Generated by Django 6.0.7 on 2026-08-04 17:03

import django.db.models.deletion
import django.db.models.manager
import educore.core.db
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_subject_course_and_more'),
        ('core', '0005_refreshtoken_isolation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodGrid',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('is_default', models.BooleanField(default=False)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'db_table': 'timetable_periodgrid',
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PeriodSlot',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('is_teaching', models.BooleanField(default=True)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='timetable.periodgrid')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'db_table': 'timetable_periodslot',
                'ordering': ['sequence'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=16)),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='core.campus')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'db_table': 'timetable_room',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledLesson',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(help_text='0 = Monday, matching datetime.weekday().')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_lessons', to='academics.classgroup')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_lessons', to='academics.course')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_lessons', to='timetable.room')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_lessons', to='timetable.periodslot')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_lessons', to='core.membership')),
            ],
            options={
                'db_table': 'timetable_scheduledlesson',
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LessonInstance',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('scheduled_start_at', models.DateTimeField()),
                ('scheduled_end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('delivered', 'Delivered'), ('verified', 'Verified'), ('missed', 'Missed'), ('abandoned', 'Abandoned'), ('excused', 'Excused'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], db_index=True, default='scheduled', max_length=16)),
                ('missed_reason', models.CharField(blank=True, max_length=200)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_instances', to='academics.classgroup')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_instances', to='academics.course')),
                ('expected_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_instances', to='core.membership')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('expected_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_instances', to='timetable.room')),
                ('scheduled_lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='timetable.scheduledlesson')),
            ],
            options={
                'db_table': 'timetable_lessoninstance',
                'ordering': ['scheduled_start_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TimetableVersion',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_versions', to='academics.academicyear')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='timetable.periodgrid')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.membership')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'db_table': 'timetable_timetableversion',
                'ordering': ['-effective_from'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='scheduledlesson',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_lessons', to='timetable.timetableversion'),
        ),
        migrations.CreateModel(
            name='CalendarException',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('kind', models.CharField(choices=[('holiday', 'Holiday'), ('exam', 'Examinations'), ('event', 'School event'), ('closure', 'Unplanned closure')], max_length=16)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('suppresses_lessons', models.BooleanField(default=True)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'db_table': 'timetable_calendarexception',
                'ordering': ['date'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
                'constraints': [models.UniqueConstraint(fields=('school', 'id'), name='timetable_calendarexception_school_id_uniq'), models.UniqueConstraint(fields=('school', 'date'), name='timetable_calendar_school_date_uniq')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='periodgrid',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='timetable_periodgrid_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='periodgrid',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='timetable_grid_school_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='periodslot',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='timetable_periodslot_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='periodslot',
            constraint=models.UniqueConstraint(fields=('grid', 'sequence'), name='timetable_slot_grid_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='periodslot',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='timetable_slot_times_ordered'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='timetable_room_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='timetable_room_school_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='lessoninstance',
            index=models.Index(fields=['school', 'date', 'status'], name='timetable_instance_day_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoninstance',
            index=models.Index(fields=['school', 'expected_teacher', 'date'], name='timetable_instance_teacher_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessoninstance',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='timetable_lessoninstance_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='lessoninstance',
            constraint=models.UniqueConstraint(fields=('scheduled_lesson', 'date'), name='timetable_instance_lesson_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='timetableversion',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='timetable_timetableversion_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='timetableversion',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='timetable_version_school_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='scheduledlesson',
            index=models.Index(fields=['version', 'weekday', 'slot'], name='timetable_scheduled_slot_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduledlesson',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='timetable_scheduledlesson_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scheduledlesson',
            constraint=models.UniqueConstraint(fields=('version', 'weekday', 'slot', 'class_group'), name='timetable_scheduled_group_slot_uniq'),
        ),
    ]
