# Generated by Django 6.0.7 on 2026-08-04 17:03

import django.db.models.deletion
import django.db.models.manager
import educore.core.db
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_refreshtoken_isolation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeOfWork',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'delivery_schemeofwork',
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.CharField(choices=[('planned', 'Arranged in advance'), ('inferred', 'Inferred when the session was opened')], default='inferred', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'delivery_substitution',
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusUnit',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('planned_periods', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'delivery_syllabusunit',
                'ordering': ['sequence'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CoverageEntry',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completion', models.CharField(choices=[('introduced', 'Introduced'), ('partial', 'Partly covered'), ('completed', 'Completed')], max_length=16)),
                ('homework_set', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'db_table': 'delivery_coverageentry',
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LessonQrRedemption',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nonce', models.CharField(max_length=64)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.membership')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'db_table': 'delivery_lessonqrredemption',
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('verification_confidence', models.PositiveSmallIntegerField(default=0)),
                ('room_changed', models.BooleanField(default=False)),
                ('late_start_minutes', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('actual_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_sessions', to='core.membership')),
            ],
            options={
                'db_table': 'delivery_lessonsession',
                'ordering': ['-opened_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
    ]
