# Generated by Django 6.0.7 on 2026-08-04 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_subject_course_and_more'),
        ('core', '0005_refreshtoken_isolation'),
        ('delivery', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsession',
            name='lesson_instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='session', to='timetable.lessoninstance'),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='timetable.room'),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='school',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school'),
        ),
        migrations.AddField(
            model_name='coverageentry',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage', to='delivery.lessonsession'),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.membership'),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.membership'),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='academics.course'),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='school',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school'),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='academics.term'),
        ),
        migrations.AddField(
            model_name='substitution',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.membership'),
        ),
        migrations.AddField(
            model_name='substitution',
            name='lesson_instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='substitution', to='timetable.lessoninstance'),
        ),
        migrations.AddField(
            model_name='substitution',
            name='original_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.membership'),
        ),
        migrations.AddField(
            model_name='substitution',
            name='school',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school'),
        ),
        migrations.AddField(
            model_name='substitution',
            name='substitute_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitutions_taken', to='core.membership'),
        ),
        migrations.AddField(
            model_name='syllabusunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='delivery.syllabusunit'),
        ),
        migrations.AddField(
            model_name='syllabusunit',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='delivery.schemeofwork'),
        ),
        migrations.AddField(
            model_name='syllabusunit',
            name='school',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school'),
        ),
        migrations.AddField(
            model_name='coverageentry',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverage_entries', to='delivery.syllabusunit'),
        ),
        migrations.AddConstraint(
            model_name='lessonqrredemption',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='delivery_lessonqrredemption_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='lessonqrredemption',
            constraint=models.UniqueConstraint(fields=('school', 'nonce', 'membership'), name='delivery_qr_nonce_member_uniq'),
        ),
        migrations.AddConstraint(
            model_name='lessonsession',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='delivery_lessonsession_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='schemeofwork',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='delivery_schemeofwork_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='schemeofwork',
            constraint=models.UniqueConstraint(fields=('course', 'term'), name='delivery_scheme_course_term_uniq'),
        ),
        migrations.AddConstraint(
            model_name='substitution',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='delivery_substitution_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='syllabusunit',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='delivery_syllabusunit_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='syllabusunit',
            constraint=models.UniqueConstraint(fields=('scheme', 'sequence'), name='delivery_unit_scheme_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coverageentry',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='delivery_coverageentry_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coverageentry',
            constraint=models.UniqueConstraint(fields=('session', 'unit'), name='delivery_coverage_session_unit_uniq'),
        ),
    ]
