# Generated by Django 6.0.7 on 2026-08-04 17:40

import django.db.models.deletion
import django.db.models.manager
import educore.core.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0002_tenant_isolation'),
        ('core', '0007_stepup_isolation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=16)),
                ('importance', models.CharField(choices=[('routine', 'Routine'), ('important', 'Important'), ('urgent', 'Urgent')], default='routine', max_length=16)),
                ('audience', models.JSONField(default=dict)),
                ('channels', models.JSONField(default=list)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('requires_acknowledgement', models.BooleanField(default=False)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='core.membership')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'db_table': 'comms_announcement',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
                'constraints': [models.UniqueConstraint(fields=('school', 'id'), name='comms_announcement_school_id_uniq')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
    ]
