# Generated by Django 6.0.7 on 2026-08-04 10:45

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import educore.core.db
import educore.presence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_campus_beacon_ids_campus_wifi_bssid_hashes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('check_in', 'Check in'), ('check_out', 'Check out')], max_length=16)),
                ('captured_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('clock_skew_seconds', models.IntegerField(default=0)),
                ('client_event_id', models.UUIDField()),
                ('payload_digest', models.CharField(max_length=64)),
                ('disposition', models.CharField(choices=[('verified', 'Verified'), ('provisional', 'Provisional'), ('rejected', 'Rejected')], max_length=16)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('rejection_reason', models.CharField(blank=True, max_length=64)),
                ('policy_version', models.PositiveIntegerField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.campus')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.device')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='core.membership')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'db_table': 'presence_attendanceevent',
                'ordering': ['captured_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('weights', models.JSONField(default=educore.presence.models.default_weights)),
                ('accept_threshold', models.PositiveSmallIntegerField(default=75)),
                ('review_threshold', models.PositiveSmallIntegerField(default=45)),
                ('min_evidence_weight', models.PositiveSmallIntegerField(default=40)),
                ('geofence_radius_m', models.PositiveIntegerField(default=150)),
                ('geofence_trusted_accuracy_m', models.PositiveIntegerField(default=50)),
                ('day_starts_at', models.TimeField(default='07:30')),
                ('day_ends_at', models.TimeField(default='17:00')),
                ('late_grace_minutes', models.PositiveSmallIntegerField(default=15)),
                ('early_checkin_minutes', models.PositiveSmallIntegerField(default=90)),
                ('max_clock_skew_seconds', models.PositiveIntegerField(default=300)),
                ('qr_token_ttl_seconds', models.PositiveIntegerField(default=30)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'db_table': 'presence_attendancepolicy',
                'ordering': ['-version'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('partial', 'Partial'), ('absent', 'Absent'), ('on_leave', 'On leave'), ('holiday', 'Holiday')], max_length=16)),
                ('disposition', models.CharField(choices=[('verified', 'Verified'), ('provisional', 'Provisional'), ('rejected', 'Rejected')], max_length=16)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('first_in_at', models.DateTimeField(blank=True, null=True)),
                ('last_out_at', models.DateTimeField(blank=True, null=True)),
                ('minutes_on_site', models.PositiveIntegerField(default=0)),
                ('resolution', models.CharField(choices=[('auto', 'Automatic'), ('reviewed', 'Reviewed'), ('overridden', 'Overridden')], default='auto', max_length=16)),
                ('policy_version', models.PositiveIntegerField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='core.membership')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'db_table': 'presence_attendancerecord',
                'ordering': ['-date'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceException',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason_code', models.CharField(choices=[('device_fault', 'Device fault'), ('no_connectivity', 'No connectivity'), ('off_site_duty', 'Off-site school duty'), ('approved_leave', 'Approved leave'), ('sick', 'Sick'), ('other', 'Other')], max_length=32)),
                ('narrative', models.TextField(blank=True)),
                ('requested_status', models.CharField(blank=True, choices=[('present', 'Present'), ('late', 'Late'), ('partial', 'Partial'), ('absent', 'Absent'), ('on_leave', 'On leave'), ('holiday', 'Holiday')], max_length=16)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('upheld', 'Upheld'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.membership')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.membership')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='presence.attendancerecord')),
            ],
            options={
                'db_table': 'presence_attendanceexception',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSignal',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal_type', models.CharField(choices=[('qr', 'Rotating QR'), ('device', 'Registered device'), ('geofence', 'Geofence'), ('wifi', 'School Wi-Fi'), ('time_window', 'Duty time window'), ('beacon', 'Bluetooth beacon'), ('face', 'Face match')], max_length=20)),
                ('verdict', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unavailable', 'Unavailable')], max_length=16)),
                ('weight_applied', models.PositiveSmallIntegerField(default=0)),
                ('hard_fail', models.BooleanField(default=False)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='presence.attendanceevent')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'db_table': 'presence_attendancesignal',
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DutySchedule',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(help_text='0 = Monday, matching datetime.weekday().', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_schedules', to='core.membership')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'db_table': 'presence_dutyschedule',
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='QrRedemption',
            fields=[
                ('id', models.UUIDField(default=educore.core.db.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nonce', models.CharField(max_length=64)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.membership')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.school')),
            ],
            options={
                'db_table': 'presence_qrredemption',
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['school', 'membership', 'captured_at'], name='presence_event_member_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendanceevent',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='presence_attendanceevent_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attendanceevent',
            constraint=models.UniqueConstraint(fields=('school', 'client_event_id'), name='presence_event_school_client_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attendancepolicy',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='presence_attendancepolicy_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attendancepolicy',
            constraint=models.UniqueConstraint(fields=('school', 'version'), name='presence_policy_school_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attendancepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school',), name='presence_policy_one_active_per_school'),
        ),
        migrations.AddConstraint(
            model_name='attendancepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('accept_threshold__gt', models.F('review_threshold'))), name='presence_policy_thresholds_ordered'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['school', 'date', 'disposition'], name='presence_record_review_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='presence_attendancerecord_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('membership', 'date'), name='presence_record_member_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attendanceexception',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='presence_attendanceexception_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attendanceexception',
            constraint=models.UniqueConstraint(condition=models.Q(('decision', 'pending')), fields=('record',), name='presence_exception_one_open_per_record'),
        ),
        migrations.AddConstraint(
            model_name='attendancesignal',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='presence_attendancesignal_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attendancesignal',
            constraint=models.UniqueConstraint(fields=('event', 'signal_type'), name='presence_signal_event_type_uniq'),
        ),
        migrations.AddConstraint(
            model_name='dutyschedule',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='presence_dutyschedule_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='dutyschedule',
            constraint=models.UniqueConstraint(fields=('membership', 'weekday'), name='presence_duty_member_weekday_uniq'),
        ),
        migrations.AddConstraint(
            model_name='qrredemption',
            constraint=models.UniqueConstraint(fields=('school', 'id'), name='presence_qrredemption_school_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='qrredemption',
            constraint=models.UniqueConstraint(fields=('school', 'nonce', 'membership'), name='presence_qr_nonce_member_uniq'),
        ),
    ]
