# Generated by Django 6.0.7 on 2026-09-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0002_tenant_isolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='checkin_reminder_lead_minutes',
            field=models.PositiveSmallIntegerField(default=45),
        ),
    ]
